name: CI

on:
  push:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Clonar repositorio

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          version: 3.12

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Run Black
        run: black --check .

      - name: Run Flake
        run: flake8 .

      - name: Testing
        run: pytest -q
